def func(a, b):
    return a + b


try:
    func()
except Exception:
    print("Ура, Ошибка!")
